@startuml classes

scale 1920*1080

package database {
    entity inters {
        inter_id int
        id_in_messenger bigint
        full_name varchar127
        messenger_type varchar127
    }

    entity messages {
        mes_id int
        mes_text text
        mes_time varchar5
        is_inter boolean
        inter_id int
    }
}

package backend {
    package forRequestsAndResponsesDbLayer {
        class Dialog {
            interId int
            idInMessenger long
            fullName String
            messengerType String
        }

        class Message {
            mesId int
            mesText String
            mesTime String
            isInter boolean
            interId int
        }
    }

    package forRequestsAndResponsesFrontendLayer {
        package getAllDialogs {
            class request {

            }

            class response {
                dialogId int
                fullName String
                messengerType String
            }
        }

        package sendMessage {
            class request {
                text String
                dialogId int
            }
        }

        package getAllMessagesByDialogId {
            class request {
                id dialogId
            }

            class response {
                text String
                time String
                isInter boolean
            }
        }
    }

}

package frontend {
    class Dialog {
        dialogId int
        fullName String
        messengerType String
    }

    class Message {
        text String
        time String
        isInter boolean
    }
}

frame notes {
    note as N1
    у фронтенда два состояния:
    - когда чат не выбран
    - - опрашиваем только диалоги
    - когда чат выбран
    - - опрашиваем диалоги
    - - и опрашиваем сообщения по айди диалогу
    end note

    note as N2
    **transformation sendMessage.request**
    **to Message for db**
    mesId = -1
    mesText = text
    mesTime - Date.now()
    isInter = false
    interId = dialogId
    end note

    note as N3
    когда кто-то пишет на бота,
    проверяем есть ли в базе данных
    диалог с таким же айди из мессенджера
    - если есть, то просто добавляем сообщение в бд
    - иначе сначала добавляем диалог в бд
    - - потом добавляем сообщение в бд
    end note
}

frontend ---> backend
backend ---> database

database --> backend
backend --> frontend

forRequestsAndResponsesFrontendLayer ---> forRequestsAndResponsesDbLayer

@enduml
